### PR TITLE
Toffy rename

### LINKED ISSUE #6: rename the repo
We could either go with a simple name (mibiscope-helper), or something more whimsical. Something like mibiscope-butler, mibiscope-assistant, or a reference to Clippy?
image

### PR DESCRIPTION
**Pull request by ngreenwald**
Renames files and directories to toffy. Closes #6

### CODE REVIEW

**Review by alex-l-kong — APPROVED** [review]
Looks and tastes good 😋

**Review by ackagel — APPROVED** [review]
looks good.  can we change this repo's name or do we have to make a new repo?

**Comment by ackagel** [comment]
> looks good. can we change this repo's name or do we have to make a new repo?

nvm looks like it can be done from settings whenever.

**Comment by ngreenwald** [comment]
Yup. Just waiting for open PRs to get merged in to avoid mega conflicts.

**Pull request merged**
